# Numpy Crash Course

In [1]:
import numpy as np

In [3]:
np.__version__ # give 2 underscore 

'1.26.4'

In [4]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# Creating Arrays

In [11]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [13]:
type(my_list)

list

# Converting list to array

In [15]:
arr=np.array(my_list)

In [17]:
arr # array is represented with array at the start.

array([0, 1, 2, 3, 4, 5])

In [19]:
type(arr)

numpy.ndarray

In [21]:
type(my_list)

list

In [ ]:
np. # np.tab = we will get lot of functions.

In [23]:
np.arange(15) # shift tab you will get docstring.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 12-03-25

In [26]:
np.arange(10) # n-1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.arange(3.0) # float

array([0., 1., 2.])

In [30]:
np.arange(0,5) # 2 argumets i.e., start index and stop index

array([0, 1, 2, 3, 4])

In [34]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [36]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [38]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [40]:
np.arange() # Atleast stop arg should be given.

TypeError: arange() requires stop to be specified.

In [42]:
np.arange(10,30,5) # 30 becomes 29. so its not included

array([10, 15, 20, 25])

In [44]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [46]:
np.arange(10,30,5,8) # It wont take 4 args

TypeError: Cannot interpret '8' as a data type

In [48]:
np.zeros(3) # parameter tuning=system by default gives the parameter. dont write 'zero'. By default it gives float
            # 1D array

array([0., 0., 0.])

In [50]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.arange(3, dtype=int) # Hyperparameter tuning = user wanted to change system parameter. Here I have changed float to int.

array([0, 1, 2])

In [54]:
np.zeros((2,2),dtype=int) # 2D array

array([[0, 0],
       [0, 0]])

In [56]:
np.zeros((2,10)) # give 2 brackets otherwise it gives you error.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [58]:
np.zeros((5,10)) # float. rows=5, columns=10

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.zeros((5,10), dtype=int) # we no need to type 'zeros' just type 'z and tab'.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [62]:
np.ones(3) # 1,s = 3 # default=float value

array([1., 1., 1.])

In [64]:
np.ones(3, dtype=int) # int

array([1, 1, 1])

In [66]:
np.ones(4, dtype=int) 

array([1, 1, 1, 1])

In [68]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [70]:
np.ones((2,2), dtype=int)

array([[1, 1],
       [1, 1]])

In [72]:
np.ones((5,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [74]:
np.twos((2,3)) # twos is not a function. And its not present in in built functions.

AttributeError: module 'numpy' has no attribute 'twos'

In [76]:
np.three((2,3))

AttributeError: module 'numpy' has no attribute 'three'

In [78]:
rand(3,2)

NameError: name 'rand' is not defined

In [80]:
random.rand(2,3)

NameError: name 'random' is not defined

In [82]:
np.random.rand(5) # np =package, random=module, rand=function

array([0.74682932, 0.73949447, 0.95500355, 0.1527429 , 0.77939668])

In [86]:
np.rand(2) # module is missing

AttributeError: module 'numpy' has no attribute 'rand'

In [90]:
np.random.rand(2) # module is given

array([0.3262401 , 0.26503781])

In [88]:
np.random.rand(2,3) # Bydefault it gives float values.

array([[0.15166869, 0.99688841, 0.73925436],
       [0.60789269, 0.29407577, 0.63512858]])

In [92]:
np.random.rand(3,5) # output will change everytime.

array([[0.39769584, 0.96641078, 0.77241582, 0.89469116, 0.16709146],
       [0.87974722, 0.70844917, 0.1068938 , 0.81655392, 0.42973073],
       [0.43570261, 0.07287623, 0.49268445, 0.82930504, 0.26115794]])

In [94]:
np.random.randint(3,5) # read doctsing shift+tab

3

In [96]:
np.random.randint(4,6)

4

In [98]:
np.random.randint(4,20) # gives random value everytime you run

15

In [104]:
np.random.randint(10,20,5) # It gives 5 ouput values. Everytime the output chnages.

array([12, 16, 15, 17, 10])

In [106]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [108]:
np.arange(1,13).reshape(3,4) # 3=rows, 4=columns.logic=> 3*4=12 its a match

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [110]:
np.arange(1,13).reshape(5,4) # logic==> 5*4=20. out of range

ValueError: cannot reshape array of size 12 into shape (5,4)

In [112]:
np.arange(1,13).reshape(6,2) # its a match.

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [114]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])