In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [5]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [9]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [11]:
type(my_list)

list

In [13]:
arr=np.array(my_list)

In [15]:
arr

array([0, 1, 2, 3, 4, 5])

In [17]:
type(arr)

numpy.ndarray

### 1.arange() = It gives the values upto the given range.

In [21]:
np.arange(15) # n-1 = 15-1 ==> 14 [0 to 14]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
np.arange(3.0) # By default the output is given in float wise.

array([0., 1., 2.])

In [25]:
np.arange(3, dtype=int) # iam changing it to integer type.so, 'dtype= datatype' that is "int"
                        # Its a 1D Array.

array([0, 1, 2])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(0,5) # it gives output from 0 to "n-1" i.e.., 0 to 4

array([0, 1, 2, 3, 4])

In [33]:
np.arange(20,10) # Always starting index should be greater than the stopping index.

array([], dtype=int32)

In [35]:
np.arange(-20,10) # it gives values from -20 to 10

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [37]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [41]:
arr=np.arange(-30,20) # we can alos write like this as well.
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [43]:
np.arange(10,10) # It cannot be same, starting index should be less than stopping index.

array([], dtype=int32)

In [45]:
np.arange() # Atleast stopping argument should be given when we have one argument.

TypeError: arange() requires stop to be specified.

In [47]:
np.arange(0,10,2) # 0=starting number, 10=stopping number, 2=step index
                  # Even numbers

array([0, 2, 4, 6, 8])

In [49]:
np.arange(0,10,3) # Odd numbers

array([0, 3, 6, 9])

In [51]:
np.arange(0,10,4,8) # It won't take 4 args

TypeError: Cannot interpret '8' as a data type

### 2. Zeros() = Always printing zeros according to the attributes given.

In [54]:
np.zeros(3) # 1D Array and It is called "Parameter Tuning" because, default is float numbers

array([0., 0., 0.])

In [56]:
np.zeros(3,dtype=int) # It is called Hyper parameter because, we changed it from float to Integer type

array([0, 0, 0])

In [58]:
np.zeros((2,2)) # 2D Array, default float value. You need to give double braces otherwise it won't recognize and won't give you output.

array([[0., 0.],
       [0., 0.]])

In [60]:
np.zeros((2,2),dtype=int) # Integer type

array([[0, 0],
       [0, 0]])

In [62]:
zero=np.zeros((2,2)) # You can aslo write like this.
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [64]:
zero=np.zeros((2,2),dtype=int)
print(zero)
print(type(zero))

[[0 0]
 [0 0]]
<class 'numpy.ndarray'>


In [66]:
np.zeros((4,6)) # 4=rows & 6=columns

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [68]:
np.zeros((3,3)) # whenever you are giving more than one arg then you need to use double braces

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [72]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [74]:
n1=(6,8) # we can write like this as well
print(np.zeros(n1)) # Parameter Tuning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [78]:
n1=(6,8) # Hyperparamter Tuning
print(np.zeros(n1,dtype=int))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


### 3. Ones() = Always printing ones according to the attributes given.

In [1]:
import numpy as np

In [3]:
np.ones(3) # It prints ones [default float number value]

array([1., 1., 1.])

In [5]:
np.ones(3,dtype=int) # Integer type

array([1, 1, 1])

In [7]:
np.ones(4)

array([1., 1., 1., 1.])

In [9]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [11]:
np.ones((3,4)) # rows=3, columns=4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.[tab] # It gives all the inbuilt functions

In [15]:
np.twos(3) # There is no 'twos' function in the inbuilt functions

AttributeError: module 'numpy' has no attribute 'twos'

In [17]:
np.threes(3) # There is no 'threes' function in the inbuilt functions

AttributeError: module 'numpy' has no attribute 'threes'

### 4. rand() =  It gives random values. The output changes each time when you run the code.

In [20]:
rand(3) # It throws you an error because you have only given function. there is no package and module.

NameError: name 'rand' is not defined

In [22]:
random.rand(3) # Here package is missing i.e., numpy(np). so it gives an error.

NameError: name 'random' is not defined

In [24]:
np.random.rand(3) # where as, np = package, random=module, rand=function.

array([0.72254938, 0.64148436, 0.6862668 ])

In [26]:
np.random.rand(3) # verytime the output changes,

array([0.9935912 , 0.16880993, 0.32696745])

In [28]:
np.random.rand(3,2) # rows=3, columns=2

array([[0.08702203, 0.78193209],
       [0.43762302, 0.39581016],
       [0.94686123, 0.5259841 ]])

In [30]:
np.random.rand(4,4) # By default it gives float values

array([[0.34983792, 0.89601301, 0.60422184, 0.78569603],
       [0.92852143, 0.95457177, 0.75287387, 0.8725135 ],
       [0.37050577, 0.2244324 , 0.1390969 , 0.05552384],
       [0.60873429, 0.5225205 , 0.44900936, 0.13400932]])

In [52]:
np.random.rand(4,10,2) # arrays=4, rows=10, columns=2

array([[[0.96408127, 0.08109996],
        [0.02689665, 0.16296667],
        [0.89759205, 0.03822517],
        [0.10681329, 0.34953458],
        [0.37886403, 0.93482402],
        [0.98580511, 0.162737  ],
        [0.29237585, 0.79693733],
        [0.58863301, 0.42490946],
        [0.7495613 , 0.5843497 ],
        [0.8340645 , 0.99542422]],

       [[0.85049278, 0.78563111],
        [0.34836859, 0.94454745],
        [0.98713786, 0.49661569],
        [0.79633365, 0.1134599 ],
        [0.02217387, 0.41762314],
        [0.72783046, 0.60526699],
        [0.5984419 , 0.33915733],
        [0.84303341, 0.76613188],
        [0.84223986, 0.88697644],
        [0.54903101, 0.62922617]],

       [[0.37630471, 0.47513881],
        [0.47038701, 0.51641953],
        [0.19696362, 0.04106931],
        [0.89690378, 0.49965239],
        [0.88389046, 0.83214637],
        [0.31600935, 0.99747977],
        [0.84543719, 0.30615926],
        [0.57039691, 0.71655169],
        [0.17102922, 0.39670062],
        [0

In [54]:
np.random.randint(10,20,2) # randint(low, high, size): This function generates random integers from a half-open interval [low, high). 
                                   # This means that low is inclusive, and high is exclusive.
                           # low: The lowest integer to be generated. In your example, low is 10.
                           # high: The highest integer to be generated (exclusive). In your example, high is 20. 
                                   # This means that the generated numbers will be less than 20.
                           # size: An integer or tuple of integers defining the shape of the output array. In your example, size is 2.
                                  # This means that the function will return an array containing 2 random integers.

array([10, 14])

In [56]:
np.random.randint(10,30,4) # 10=low, 30=high, 4=no.of values as output.
                           # each time it gives 4 random values as output.

array([20, 15, 18, 11])

In [64]:
np.random.randint(2,8,2) # It only gives integer values. its a default function.

array([4, 2])

In [70]:
np.random.randint(10,20,(10,10)) # [10,10]= its like 2d matrix and its a tuple.
                                 # low=10,high=20
                                 # It generates values in between 10 to 19.

array([[11, 19, 15, 13, 14, 15, 11, 10, 13, 18],
       [12, 19, 10, 19, 12, 13, 10, 16, 15, 18],
       [10, 12, 11, 19, 17, 14, 16, 12, 15, 14],
       [18, 18, 13, 10, 14, 16, 16, 13, 13, 15],
       [16, 18, 12, 19, 11, 13, 16, 12, 14, 15],
       [15, 16, 16, 11, 18, 16, 13, 13, 19, 17],
       [18, 11, 14, 19, 10, 19, 16, 12, 15, 13],
       [12, 12, 11, 10, 14, 13, 10, 11, 14, 11],
       [17, 10, 16, 14, 18, 12, 15, 14, 14, 19],
       [13, 19, 15, 10, 18, 10, 19, 16, 11, 13]])

In [74]:
np.random.randint(1,100,(5,5)) # It gives random values. Everytime it changes.

array([[54, 30, 29, 57, 66],
       [ 5, 51, 34, 63, 40],
       [ 6, 85,  2, 63, 69],
       [64, 79, 71, 43, 20],
       [57, 15, 39, 85, 21]])

### 5. reshape() = It does not modify the underlying data of the array; it only changes how the data is organized.

In [85]:
np.arange(1,13).reshape(3,4) # remember= (3,4)=>3*4=12
                             # Here 13= n-1=> 12
                             # It should match otherwise it gives you error.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [89]:
np.arange(1,15).reshape(2,7) # 15=n-1=>14 and 2*7=14. Its a match.

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [91]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.arange(1,22).reshape(3,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [97]:
b = np.random.randint(10,20,(5,4))
b

array([[13, 13, 16, 13],
       [17, 15, 17, 18],
       [12, 10, 13, 16],
       [14, 14, 12, 17],
       [13, 10, 13, 12]])

In [99]:
type(b)

numpy.ndarray

In [101]:
b[:] # It prints all the elements

array([[13, 13, 16, 13],
       [17, 15, 17, 18],
       [12, 10, 13, 16],
       [14, 14, 12, 17],
       [13, 10, 13, 12]])

In [103]:
b[1:3] # Here each row is one index value. 3=n-1=>2. so 1 and 2 is output.

array([[17, 15, 17, 18],
       [12, 10, 13, 16]])

In [107]:
b[3:5] # last two rows as output

array([[14, 14, 12, 17],
       [13, 10, 13, 12]])

In [113]:
b

array([[13, 13, 16, 13],
       [17, 15, 17, 18],
       [12, 10, 13, 16],
       [14, 14, 12, 17],
       [13, 10, 13, 12]])

In [117]:
b[1,3] # Here rows and columns starts with '0'. that is row=0,1,2,3 and columns= 0,1,2,3,4
       # So row=1 and column(3)=18
       # so output=18

18

In [119]:
b[4,1] # last row second column digit is '10'

10

In [121]:
b[1,-1] # -1= last element of the first row.

18

In [123]:
b[2,-1] # last element of 2nd row.

16

In [129]:
b[2:3] # start=2ndrow and stop=3 = no.of line row
       # start = inclusive and stop = exclusive

array([[12, 10, 13, 16]])

In [133]:
b[4:5] # start= 4th row and stop = 5th row

array([[13, 10, 13, 12]])

In [139]:
b[:,1] # this is for column output. : = all and 1= 1st column(index value)
       # ',' is very important. otheriwse it will give output for row.

array([13, 15, 10, 14, 10])

In [143]:
b[:, 2] # column syntax: [:,column number]

array([16, 17, 13, 12, 13])

In [147]:
b

array([[13, 13, 16, 13],
       [17, 15, 17, 18],
       [12, 10, 13, 16],
       [14, 14, 12, 17],
       [13, 10, 13, 12]])

In [153]:
b[-4,-2] # -4 = last to 4th row and -2 = last to second column.

15

In [5]:
import numpy as np

In [21]:
n=np.arange(1,101) # Like this you can get any set of numbers you want as a matrix.
n.reshape(5,20)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [7]:
b=np.random.randint(10,20,(4,4))

In [9]:
b

array([[19, 14, 19, 16],
       [15, 16, 11, 13],
       [14, 12, 13, 16],
       [15, 13, 10, 13]])

In [15]:
b[-4,-1] # 1st line last element that is -1th element

16

In [21]:
b[-4:2]

array([[19, 14, 19, 16],
       [15, 16, 11, 13]])

# Operations

In [26]:
a=np.random.randint(10,20,5)
a

array([15, 17, 19, 13, 16])

In [28]:
id(a) # Address of the memory location.

2999489329648

In [38]:
my_list=[0,1,2,3,4,5]
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [42]:
arr2=np.random.randint(1,100,(10,10))
arr2

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32],
       [96, 64, 27, 84, 75, 36, 72, 24, 47, 90],
       [53, 60, 36, 60,  8, 25, 22, 60, 31,  2],
       [30, 56, 10, 89, 14, 42, 43, 15, 85, 57],
       [61, 48, 48, 54, 57,  9, 64, 66, 98, 94]])

In [46]:
arr2[:]

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32],
       [96, 64, 27, 84, 75, 36, 72, 24, 47, 90],
       [53, 60, 36, 60,  8, 25, 22, 60, 31,  2],
       [30, 56, 10, 89, 14, 42, 43, 15, 85, 57],
       [61, 48, 48, 54, 57,  9, 64, 66, 98, 94]])

In [48]:
arr2[:4]

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77]])

In [50]:
arr2[:-4]

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32]])

In [52]:
arr2[-4:]

array([[96, 64, 27, 84, 75, 36, 72, 24, 47, 90],
       [53, 60, 36, 60,  8, 25, 22, 60, 31,  2],
       [30, 56, 10, 89, 14, 42, 43, 15, 85, 57],
       [61, 48, 48, 54, 57,  9, 64, 66, 98, 94]])

In [54]:
arr2[0:5] # ':' it represents slicing

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17]])

In [56]:
arr2

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32],
       [96, 64, 27, 84, 75, 36, 72, 24, 47, 90],
       [53, 60, 36, 60,  8, 25, 22, 60, 31,  2],
       [30, 56, 10, 89, 14, 42, 43, 15, 85, 57],
       [61, 48, 48, 54, 57,  9, 64, 66, 98, 94]])

In [58]:
arr2[1,4] # ',' this will give you the particular element

57

In [60]:
arr2[-5,5] # left side = top to bottom it starts with '0'
           # right side = bottom to top it starts with '-1'

65

In [64]:
arr2[-5,-6]

39

In [66]:
arr2

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32],
       [96, 64, 27, 84, 75, 36, 72, 24, 47, 90],
       [53, 60, 36, 60,  8, 25, 22, 60, 31,  2],
       [30, 56, 10, 89, 14, 42, 43, 15, 85, 57],
       [61, 48, 48, 54, 57,  9, 64, 66, 98, 94]])

In [68]:
arr2[::-1] # reverse of a matrix

array([[61, 48, 48, 54, 57,  9, 64, 66, 98, 94],
       [30, 56, 10, 89, 14, 42, 43, 15, 85, 57],
       [53, 60, 36, 60,  8, 25, 22, 60, 31,  2],
       [96, 64, 27, 84, 75, 36, 72, 24, 47, 90],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [99, 96, 45, 53, 10, 87, 51,  7, 12, 91]])

In [70]:
arr2[::-2] # It skips 2 rows and gives output in a reverse

array([[61, 48, 48, 54, 57,  9, 64, 66, 98, 94],
       [53, 60, 36, 60,  8, 25, 22, 60, 31,  2],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63]])

In [72]:
arr2[:-3]

array([[99, 96, 45, 53, 10, 87, 51,  7, 12, 91],
       [37, 71, 61, 64, 57, 92, 97, 62, 81, 63],
       [80, 33, 16, 89, 38, 76, 67, 51, 21, 28],
       [50,  8, 49, 25, 18, 17, 15, 67,  7, 77],
       [28, 80, 38, 44, 81, 37, 51, 49, 26, 17],
       [62, 73, 11,  8, 39, 65, 16, 74, 10, 32],
       [96, 64, 27, 84, 75, 36, 72, 24, 47, 90]])

In [74]:
arr

array([0, 1, 2, 3, 4, 5])

In [76]:
arr.max() # It gives maximum value

5

In [78]:
arr.min() # It gives maximum value

0

In [80]:
arr. mean() # It gives mean value i.e., 2.5

2.5

In [84]:
arr.median() # It is because median in not in built function. 
             # Use "from numpy import *" where * = import all numpy libraries.

NameError: name 'numpy' is not defined

In [86]:
from numpy import *

In [94]:
median(arr)

2.5

In [96]:
arr3=array([1,2,3,4,5,6,7,8,9,10]) # median() works now
median(arr3)

5.5

In [104]:
arr3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [106]:
arr

array([0, 1, 2, 3, 4, 5])

In [108]:
arr.reshape(2,3,order='C') # order='C' is used, the elements are taken from the original array in their original order (1, 2, 3, 4, 5, 6)
                           # And placed into the 2x3 array row by row.
                          # In simple words, orderwise output. 

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
arr.reshape(2,3,order='F') #The original array arr is [0, 1, 2, 3, 4, 5].
                           # With order='F', the reshape() function fills the new 2x3 array column by column:
                            # The first column is filled with the first two elements: 0 and 1.
                            # The second column is filled with the next two elements: 2 and 3.
                            # The third column is filled with the last two elements: 4 and 5.
                            # output=[0,2,4] & [1,3,5]

array([[0, 2, 4],
       [1, 3, 5]])

In [120]:
arr.reshape(2,3,order='A') # Its almost same as "Order C"

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [125]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [131]:
row=4
col=5

In [137]:

row

4

In [139]:
col

5

In [141]:
mat[row,col]

45

In [143]:
mat[4,5] # 4=row and 5=column. the integer is "45"

45

In [145]:
mat[6] # row as output

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [147]:
mat[:,6] # Column as output

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [149]:
mat[4,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [153]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [155]:
mat[:-1] # difference between the "," and ":"

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [157]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [163]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [165]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [175]:
mat[2:6,2:4]    # 2:6: This part specifies the rows to select.
                # row:
                # 2 is the starting row index (inclusive).
                # 6 is the ending row index (exclusive).
                # Therefore, this selects rows with indices 2, 3, 4, and 5.
                # column:
                # 2:4: This part specifies the columns to select.
                # 2 is the starting column index (inclusive).
                # 4 is the ending column index (exclusive).
                # Therefore, this selects columns with indices 2 and 3.

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [177]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [185]:
mat[4:6,4:8]

array([[44, 45, 46, 47],
       [54, 55, 56, 57]])

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [189]:
mat[6:9,5:8] # row=6:9, that is i want the values from 6th to 8th row. 9-1=8
             # column=5:8 that is i want values from 5th to 7th column. 8-1=7

array([[65, 66, 67],
       [75, 76, 77],
       [85, 86, 87]])

# Masking

In [192]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [194]:
id(mat)

2999491873168

In [198]:
mat<50 # It gives boolean expression as "True" upto 49 numbers.

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [200]:
mat<=50 # Now 50 also included.

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [202]:
mat[mat<50] # To get integer values. we need to use extra "mat"

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [204]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [206]:
mat[mat==50]

array([50])

In [208]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])